//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YPCWorkshopWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public int rentalId { get; set; }
        public System.DateTime checkOut { get; set; }
        public Nullable<System.DateTime> checkIn { get; set; }
        public int volunteerId { get; set; }
        public int toolId { get; set; }
    
        public virtual Tool Tool { get; set; }
        public virtual Volunteer Volunteer { get; set; }
    }
}
